### ISSUE TITLE
Error in docker build

### ISSUE THREAD

**Issue by jagathan** [tyrex-team/sparqlgx#1] opened 2017-12-11 15:11 UTC
Hi,
I am trying to build spraqlgx using docker and when I run `docker build -t sparqlgx .` I get:

[ERROR] The compilation of cppo failed at "jbuilder build -p cppo -j 4".
[ERROR] The compilation of easy-format failed at "jbuilder build -p easy-format
        -j 4".
[menhir: make Makefile] Command started
∗  installed menhir.20171206

#=== ERROR while installing cppo.1.6.0 ========================================#
 opam-version         1.2.2
 os                   linux
 command              jbuilder build -p cppo -j 4
 path                 /opt/sparqlgx/.opam/system/build/cppo.1.6.0
 compiler             system (4.02.3)
 exit-code            127
 env-file             /opt/sparqlgx/.opam/system/build/cppo.1.6.0/cppo-441-50de41.env
 stdout-file          /opt/sparqlgx/.opam/system/build/cppo.1.6.0/cppo-441-50de41.out
 stderr-file          /opt/sparqlgx/.opam/system/build/cppo.1.6.0/cppo-441-50de41.err

#=== ERROR while installing easy-format.1.3.0 =================================#
 opam-version         1.2.2
 os                   linux
 command              jbuilder build -p easy-format -j 4
 path                 /opt/sparqlgx/.opam/system/build/easy-format.1.3.0
 compiler             system (4.02.3)
 exit-code            127
 env-file             /opt/sparqlgx/.opam/system/build/easy-format.1.3.0/easy-format-441-982793.env
 stdout-file          /opt/sparqlgx/.opam/system/build/easy-format.1.3.0/easy-format-441-982793.out
 stderr-file          /opt/sparqlgx/.opam/system/build/easy-format.1.3.0/easy-format-441-982793.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install biniou 1.2.0
  ∗  install yojson 1.4.0
The following actions failed
  ∗  install cppo        1.6.0
  ∗  install easy-format 1.3.0
The following changes have been performed
  ∗  install base-bytes      base      
  ∗  install base-ocamlbuild base      
  ∗  install conf-m4         1         
  ∗  install conf-which      1         
  ∗  install jbuilder        1.0+beta16
  ∗  install menhir          20171206  
  ∗  install ocamlbuild      0         
  ∗  install ocamlfind       1.7.3     

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20171111150701.export"
The command '/bin/sh -c opam init -a &&     echo ". /opt/sparqlgx/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true" > ~/.bashrc &&     opam install -y menhir yojson' returned a non-zero code: 4

Any ideas?
Thanks!

**Comment by louisjac** [comment] 2017-12-11 15:54
Hi,

Thanks for the clear bug report.

I managed to reproduce on HEAD version and fix the problems I was having (see commit attached)

Could you test the new dockerfile (either by checkouting or cherrypicking this patch to the version of sgx you are using) and report to us if it works?

**Comment by jagathan** [comment] 2017-12-14 08:39
Hi,
Thanks a lot for your quick response!
I used the new dockerfile and everything works fine now. I was able to find the HDFS bug by myself but the other one was not very clear to me. 

Thanks!

**Comment by louisjac** [comment] 2017-12-14 08:49
Cool!

For all project maintainers, the ocaml part of the issue was likely caused by a mismatch between ocaml versions of packages for debian and opam versions which can sometimes happen (and we should always use the opam version). 

@jagathan  I am closing the issue but come to us if you have other problems!

**Closed as completed by louisjac** 2017-12-14 08:49 UTC
